config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'

  resources :tracks
  resources :static
  resources :samplepacks
  resources :albums
  resources :demos,            path: :sound_design
  resources :ghostproductions, path: :band_production
  # resources :carts, only: [:edit]
  
  get '/contact/', to: 'static#contact', as: 'contact'
end

app/models/track.rb
class Track < ApplicationRecord
    # has_many :cart_items, as: :cartable
    # has_many :carts, through: :cart_items, source: :cart
    belongs_to :album, optional: true, touch: true
    has_many :urls, dependent: :destroy
    accepts_nested_attributes_for :urls, allow_destroy: true, reject_if: proc { |att| att['link'].blank? }

    # accept_nested_attributes_for :

    has_one_attached :audio_file
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :current_user_is_admin?, except: [:index, :show]
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  def index
    @tracks = Track.all
  end

  def show
  end

  def new
    @track = Track.new
  end
  
  def create
    @track = Track.new(track_params)
    respond_to do |format|
      if @track.save
        format.html { redirect_to root_path, notice: 'Track added' }
        format.json {  }
      else
        format.html { redirect_to root_path, notice: 'Error' }
        format.json {  }
      end
    end
  end

  def edit
    @albums = Album.includes(:name).all
  end

  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track updated' }
        format.json {  }
      else
        format.html { redirect_to root_path, notice: 'Error' }
        format.json {  }
      end
    end
  end

  def destroy
    @track.destroy
    redirect_to tracks_path, flash: { success: 'Track deleted' }
  end

  private

  def track_params
    params.require(:track).permit(:name, urls_attributes: Url.attribute_names.map(&:to_sym).push(:_destroy))
  end

  def set_track
    @track = Track.find(params[:id])
  end
end

app/views/tracks/_form_add_link.html.erb
<%= form_for @track, url: {action: "update"} do |f| %>
  <table class="table">
    <tbody class="fields">
      
      <%= f.fields_for :urls do |builder| %>
        <%= render 'urls/form', f: builder %>
      <% end %>
    </tbody>
  </table>
  <%= link_to_add_url('Add a link', f, :urls, class: ' btn btn-outline-light float-right') %>
  <%= f.submit class: 'btn btn-block btn-primary'  %>
<% end %>

app/views/tracks/_form_new.html.erb
<tr>
  <td><%= f.text_field :name, label: false, class: 'form-control col', placeholder: 'Track name' %></td>
  <td>
    <%= f.hidden_field :_destroy %>
    <%= link_to 'Delete', '#', class: 'remove_record text-danger float-right' %>
  </td>
</tr>

app/views/tracks/_track_table.html.erb
<table class="table">
  <tbody>
    <tr>
      <td><%= link_to track.name, track_path(track) %></td>
      <td>
        <%= action_button('Edit', edit_track_path(track)) %>
        <%= delete_button('Delete', track) %>
      </td>
    </tr>
  </tbody>
</table>

app/views/tracks/edit.html.erb
<div>
  <%= form_for @track, url: {action: "update"} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <%= f.submit %>
  <% end %>
</div>

app/views/tracks/index.html.erb
<div class="container">
  <%= render partial: 'tracks/track_table', collection: @tracks, as: 'track', cached: true %>

  <%= action_button('Add a track', new_track_path) %>

</div>

app/views/tracks/new.html.erb
<div>
  <%= form_for @track, url: {action: "create"} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
  <% end %>
</div>

app/views/tracks/show.html.erb
<div class="container">
  <h1><%=  @track.name %></h1>
  <div class="jumbotron">
    <div class="row"> 
      <div class="col-md-10 offset-md-1">
        <div class="row">
          <div class="col-md-7 text-center">
            <%= image_tag url_for(@track.album.large) %>
          </div>
          <div class="col-md-5">
            <h4>Listen on:</h4>

            <% @track.urls.each do |url| %>
              <% cache url do %>
                <%= display_track_link(url.link) %>
              <% end %>
            <% end %>

          </div>
        </div>

        <% if user_signed_in? && current_user.admin == true %>
          <%= render 'tracks/form_add_link', cached: true %>
        <% end %>

      </div>
    </div>
  </div>