config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'

  resources :tracks
  resources :static
  resources :samplepacks
  resources :albums
  resources :demos,            path: :sound_design
  resources :ghostproductions, path: :band_production
  # resources :carts, only: [:edit]
  
  get '/contact/', to: 'static#contact', as: 'contact'
end

app/models/album.rb
class Album < ApplicationRecord
  include NamableConcern
  include ArtworkableConcern

  has_many :tracks, dependent: :destroy
  accepts_nested_attributes_for :tracks, allow_destroy: true, reject_if: proc { |att| att['name'].blank? }

  # has_many :cart_items, as: :cartable
  # has_many :carts, through: :cart_items, source: :cart

  validates :release_date, presence:   { message: ': album should have a release date.' }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :current_user_is_admin?, except: [:index, :show]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all.includes(:tracks)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
    @album.tracks.build
  end

  def edit
    @album.tracks.build
  end

  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, flash: { success: "Album added" } }
        format.json {  }
      else
        format.html { render action: :new, flash: { error: "Something wrong happened :(" } }
        format.json {  }
      end
    end
  end

  def update
    @album.update(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, flash: { success: "Album edited" } }
        format.json {  }
      else
        format.html { redirect_back fallback_location: root_path, flash: { error: "Something wrong happened :(" } }
        format.json {  }
      end
    end
  end

  def destroy
    @album.destroy
    
    redirect_to albums_path, flash: { success: 'Album deleted' }
  end

	private

  def album_params
    params.require(:album).permit(:name, :release_date, :album_artwork, :url, tracks_attributes: Track.attribute_names.map(&:to_sym).push(:_destroy))
  end

  def set_album
    @album = Album.find(params[:id])
  end
end

app/views/albums/_form_add_track.html.erb
<div class="col form-group">
  <table class="table">
    <tbody class="fields">
      <% f.fields_for :tracks do |builder| %>
        <%= render 'tracks/form', f: builder, cached: true %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/albums/_form_new.html.erb
<div class="form-row mt-5">
  <div class="col-md-6">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Album title' %>
  </div>

  <div class="col-md-6">
    <%= f.label :release_date %>
    <%= f.date_field :release_date, class: 'form-control' %>
  </div>
</div>

<div class="custom-file mt-3">
  <%= f.label :album_artwork, class: "custom-file-label" %>
  <%= f.file_field :album_artwork, class: 'custom-file-input' %>
</div>

<!-- Add track -->
<h2 class="text-center pt-5">Add tracks</h2>
<table class="table">
  <tbody class="fields">
    <% f.fields_for :tracks do |builder| %>
      <%= render 'tracks/form_new', f: builder %>
    <% end %>
  </tbody>
</table>

<%= link_to_add_track('Add a track', f, :tracks, class: ' btn btn-outline-info float-right mb-3') %>

<div class="mt-5">
  <%= f.submit class: 'btn btn-block btn-outline-primary'  %>
</div>

app/views/albums/_hoverable_album.html.erb
<!-- ALBUM: <%= album.name %> hoverable image -->
<div class="col-lg-4 col-md-4 col-sm-5 col-12 artwork-container">
  <%= image_tag album.large, class: "image img-fluid pb-2 filter #{album.class.to_s.downcase}" %>
  <div class="middle">
    <div class="text">

      <%= link_to album_path(album) do %>
        <i class="far fa-eye pr-2"></i><% end %>
      
      <%= link_to nil do %>
        <i class="fas fa-volume-up"></i>
      <% end %>
      
    </div>
  </div>
</div>

app/views/albums/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h1>Edit <%= @album.name %></h1>
      <h3>Artwork</h3>
      <div class="col text-center">
        <%= image_tag @album.large %>
      </div>

      <%= form_for @album, url: {action: 'update'}, method: :put do |f| %>
        <div class="col-md offset-4 form-group">
          <%= f.file_field :album_artwork, class: 'form-control-file' %>
        </div>

        <h3>Title</h3>
        <div class="col form-group">
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <h2 class="text-center">Tracks</h2>
        <table class="table">
          <tbody class="fields">
          <%= f.fields_for :tracks do |builder| %>
            <% render 'tracks/form', f: builder %>
          <% end %>
          </tbody>
        </table>
        
        <%= link_to_add_track('Add a track', f, :tracks, class: ' btn btn-outline-info float-right') %>

        <%= f.submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/albums/index.html.erb
<div class="container pt-5">
  <h1 class="mb-5 text-lg-left d-inline-block">Music</h1>
  <div class="d-inline-block float-right">
    <%= action_button('Add new album', new_album_path) %>
  </div>
  <div class="ml-5 mb-5">
    <h2>Latest release</h2>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 text-center">
        <%= link_to album_path(@albums.last) do %>
          <%= image_tag @albums.last.large, class: "img-fluid" %>
        <% end %>
      </div>
      <div class="col-8">
        <h3><%= link_to @albums.last.name, album_path(@albums.last) %></h3>
        <%= action_link('Edit ', edit_album_path(@albums.last)) %> - 
        <%= delete_link('Delete ', @albums.last) %>

        <p><%= pluralize(@albums.last.tracks.size, 'track') %></p>
        <%= render 'tracks/track_table', collection: @albums.last.tracks, as: 'track', cached: true %>
      </div>
    </div>
  </div>

  <!-- <div class="scrolling-wrapper">
    <div class="right-arrow"></div>
    <div class="horizontal-scroll">
    <div class="horizontal-img-container">
    <% @albums.each do |album| %>
      <% cache album do %>
        <div class="box">
        <%= image_tag album.large, class:'img-fluid' %>
        </div>
      <% end %>
    <% end %>
    </div>
    </div>
    <div class="left-arrow"></div>
    </div> -->



    <div class="jumbotron">
      <div class="row">
        <% @albums.each do |album| %>
          <%# cache album do %>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mb-3">
              <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                  <%= link_to album_path(album) do %>
                    <%= image_tag album.large, class: "img-fluid" %>
                  <% end %>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                  <h4><%= link_to album.name, album_path(album) %></h4>
                  <%= action_link('Edit', edit_album_path(album)) %> - 
                  <%= delete_link('Delete', album) %>
                  <p><%= pluralize(album.tracks.size, 'track') %></p>
                </div>
              </div>
            </div>
          <%# end %>
        <% end %>
      </div>
    </div>


    <%#
      <style>
.scrolling-wrapper {
  width: 100%;
  height: 100px;
  position: relative;
}

.box  {
  float: left;
  margin: 0 10px 0 0;
  width: 100px;
  display: block;
}

.horizontal-img-container {
  position: absolute;
  left: 0;
  width: <%= @albums.all.size * 110 %><%# px;
}

    .horizontal-scroll {
    width: 81%;
    height: 100%;
    position: absolute;
    left: 8%;
    margin-left: 0%;
    overflow: hidden;x
  }

    .left-arrow {

    width:40px;
    height:40px;
    background:#ff0000; 
      position:absolute;
    left:0px;
  }

    .right-arrow {

    width:40px;
    height:40px;
    background:#ff0000; 
      position:absolute;
    right:0px;
  }
  </style>

  <script>
  var view = $(".horizontal-img-container");
  var move = "110px";
  var containerElements = $('.box').length
  var sliderLimit =  containerElements * -110
  console.log(sliderLimit)

  $(".right-arrow").click(function(){

    var currentPosition = parseInt(view.css("left"));
    if (currentPosition >= sliderLimit) view.stop(false,true).animate({left:"-="+move},{ duration: 400})
      console.log(currentPosition)
  });

  $(".left-arrow").click(function(){

    var currentPosition = parseInt(view.css("left"));
    if (currentPosition < 0) view.stop(false,true).animate({left:"+="+move},{ duration: 400})
      console.log(currentPosition)
  });
  </script>
%>

app/views/albums/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">

      <h2 class="text-center">Add a new album</h2>
      
      <%= form_for @album, url: {action: 'create'} do |f| %>
        <%= render 'shared/form_errors', f: f %>
        <%= render 'albums/form_new', f: f %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="row">
        <div class="col-md-5">
          <%= image_tag url_for(@album.large), class: "img-fluid" %>
          <h1></h1><%= pluralize(@album.tracks.count, 'track') if @album.tracks.any? %></h1>
        </div>
        <div class="col-md-7 pl-5">
          <h3><%= @album.name %></h3>
          <table class="table">
            <% @album.tracks.each do |track| %>
              <% cache track do %>
                <tr>
                  <td>
                    <%= link_to track.name, track_path(track) %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </table>
        </div>
    </div>
    
    <%= action_button('Edit', edit_album_path(@album)) %>
    <%= delete_button('Delete', @album) %>

  </div>
</div>