config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'

  resources :tracks
  resources :static
  resources :samplepacks
  resources :albums
  resources :demos,            path: :sound_design
  resources :ghostproductions, path: :band_production
  # resources :carts, only: [:edit]
  
  get '/contact/', to: 'static#contact', as: 'contact'
end

app/models/samplepack.rb
class Samplepack < ApplicationRecord
  include NamableConcern
  include ArtworkableConcern

  has_many :samplepack_sample, dependent: :destroy
  has_many :samples, through: :samplepack_sample, dependent: :destroy

  has_many :cart_items, as: :cartable
  has_many :carts, through: :cart_items, source: :cart


  validates :release_date, presence:   { message: ': samplepack should have a release date.' } 
  validates :url,          presence:   { message: ': samplepack should have an URL' }
  validates :price,        presence:   { message: ': samplepack should have a price' }
end

app/controllers/samplepacks_controller.rb
class SamplepacksController < ApplicationController
  before_action :current_user_is_admin?, except: [:index, :show]
  before_action :set_samplepack, only: [:show, :edit, :update, :destroy]

  def index
    @samplepacks = Samplepack.all
  end

  def show
  end

  def new
    @samplepack = Samplepack.new
  end

  def create
    @samplepack = Samplepack.new(samplepack_params)
    respond_to do |format|
      if @samplepack.save
        format.html { redirect_to @samplepack, flash: { success: "Samplepack added !"} }
        format.json {   }
      else
        format.html { render action: :new, flash: { error: "Something wrong happened :(" } }
        format.json {   }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @samplepack.update(samplepack_params)
        format.html { redirect_to samplepacks_path, flash: { success: 'Samplepack updated' } }
        format.json {  }
      else
        format.html { render action: :edit, flash: { notice: 'Something wrong happened :(' } }
        format.json {  }
      end
    end
  end

  def destroy
    @samplepack.destroy
    redirect_to samplepacks_path, flash: { success: 'Samplepack deleted' }
  end

  private

  def samplepack_params
    params.require(:samplepack).permit(:name, :release_date, :price, :album_artwork, :url)
  end

  def set_samplepack
    @samplepack = Samplepack.find(params[:id])
  end
end

app/views/samplepacks/_form_new.html.erb
<div class="form-row mt-5">
  <div class="col-md-6">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Samplepack name" %>
  </div>

  <div class="col-md-6">
    <%= f.label :release_date %>
    <%= f.date_field :release_date, class: "form-control" %>
  </div>

  <div class="col-10">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control", placeholder: "Third party URL"%>
  </div>

  <div class="col-2">
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div>
</div>

  <div class="custom-file mt-3">
    <%= f.label :album_artwork, class: "custom-file-label" %>
    <%= f.file_field :album_artwork, class: "custom-file-input" %>
  </div>

<div class="mt-5">
  <%= f.submit class: "btn btn-block btn-outline-primary" %>
</div>

app/views/samplepacks/_hoverable_samplepack.html.erb
<!-- SAMPLEPACK: <%= samplepack.name %> -->
<div class="col-lg-4 col-md-4 col-sm-5 col-12 artwork-container">
  <%= image_tag samplepack.large, class: "img-fluid pb-3 filter #{samplepack.class.to_s.downcase}" %>
  <div class="middle">
    <div class="text">

    <%= link_to samplepack_path(samplepack) do %>
      <i class="far fa-eye", style="padding-right: 10px;"></i><% end %>

    <%= link_to samplepack.url.html_safe do %>
      <i class="fas fa-shopping-cart"></i>
    <% end %>
    
    </div>
  </div>
</div>

app/views/samplepacks/_hoverable_with_text.html.erb
<div class="col-lg-4 col-md-4 col-sm-5 col-12 artwork-container mb-3">
  <%= image_tag samplepack.large, class: "img-fluid pb-3 filter #{samplepack.class.to_s.downcase}" %>
  <div class="middle">
    <div class="text">

    <%# TODO when Stripe will be integrated %>
    <%= link_to samplepack_path(samplepack) do %>
      <i class="far fa-eye", style="padding-right: 10px;"></i><% end %>

    <%= link_to samplepack.url.html_safe do %>
      <i class="fas fa-shopping-cart"></i>
    <% end %>
    
    </div>
  </div>
  <span class="d-block"><%= link_to samplepack.name, samplepack_path(samplepack) %></span>
  <% if (samplepack.price == 0) || (samplepack.price == nil) %>
    <span class="d-block">Free</span>  
  <% else %>
    <span class="d-block">€ <%= samplepack.price %></span>
  <% end %>
</div>

app/views/samplepacks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">

    <%= image_tag url_for(@samplepack.large), class: "img-fluid" %>
    
    <%= delete_button('Delete', @samplepack) %>
    
    <h2 class="text-center">Edit <%= @samplepack.name %></h2>

    <%= form_for @samplepack, url: {action: "update"} do |f| %>
      <%= render "samplepacks/form_new", f: f, cached: true %>
    <% end %>
    
    </div>
  </div>
</div>

app/views/samplepacks/index.html.erb
<div class="container pt-5">
  <h1 class="mb-5 text-lg-left d-inline-block">Samplepacks</h1>
  <div class="d-inline-block float-right">
    <%= action_button('Add a samplepack', new_samplepack_path) %>
  </div>

  <div class="row">
    <%= render 'samplepacks/hoverable_with_text', collection: @samplepack, as: samplepack, cached: true %>
  </div>
</div>

app/views/samplepacks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
   
      <h2 class="text-center">Add a new samplepack</h2>

      <%= form_for @samplepack, url: {action: 'create'} do |f| %>
        <%= render 'shared/form_errors', f: f %>
        <%= render "samplepacks/form_new", f: f, cached: true %>
      <% end %>

    </div>
  </div>
</div>

app/views/samplepacks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="row">
        <div class="col-md-5">
          <%= image_tag url_for(@samplepack.large), class: "img-fluid" %>
        </div>
        <div class="col-md-7 pl-5">
          <h3><%= @samplepack.name %></h3>
          
        </div>
    </div>

    <%= link_to @samplepack.url.html_safe do %>
      <button class='btn btn-outline-primary float-right mr-6 ml-2'>Buy</button>
    <% end %>

    <%= action_button('Edit', edit_samplepack_path(@samplepack)) %>
    <%= delete_button('Delete', @samplepack) %>

  </div>
</div>