config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'

  resources :tracks
  resources :static
  resources :samplepacks
  resources :albums
  resources :demos,            path: :sound_design
  resources :ghostproductions, path: :band_production
  # resources :carts, only: [:edit]
  
  get '/contact/', to: 'static#contact', as: 'contact'
end

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to 'Manel Bach Ramires', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Band production', ghostproductions_path, class: 'nav-link' %>
      <li>

      <li class="nav-item">
          <%= link_to 'Sound design', demos_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Samplepacks', samplepacks_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Music release', albums_path, class: 'nav-link' %>
      </li>
      
      <li class="nav-item">    
        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
      </li>
    </ul>
		<li class="nav-item dropdown list-unstyled">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<i class="far fa-user mr-5", style="color:white"></i>
        </a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<% if current_user %>
						<%# link_to 'Profil', edit_user_registration_path, class: "dropdown-item" %>
						<%# link_to 'Cart', edit_cart_path, class: "dropdown-item" %>
						<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
					<% else %>
						<%= link_to 'Sign up', new_user_registration_path, class: "dropdown-item" %>
						<%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
					<% end %>
				</div>
    </li>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: :psj, action: action_name, controller: controller_name %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/alerts' %>

    <%= yield %>
    
  </body>
</html>